// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export default {
    "aws_appsync_graphqlEndpoint": "https://ofb47msgevdobgdzk5sjvcecry.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4i5f3l2oczdxvnpneiwl2nufza",
};

